---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    provider: porkadot
  name: porkadot-kubernetes
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/component: kube-apiserver
    app.kubernetes.io/managed-by: porkadot
  loadBalancerIP: 172.18.14.1
  ports:
  - name: https
    port: 6443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    provider: porkadot
  name: porkadot-kubernetes-latest
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/component: kube-apiserver
    app.kubernetes.io/instance: kube-apiserver-porkadot
    app.kubernetes.io/managed-by: porkadot
    app.kubernetes.io/name: kube-apiserver
    app.kubernetes.io/version: v1.22.1
    app.kubernetes.io/part-of: kubernetes
    k8s-app: kube-apiserver
  ports:
  - name: https
    port: 6443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig-in-cluster
  namespace: kube-system
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - name: local
      cluster:
        server: https://172.18.14.1:6443
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
    - name: service-account
      user:
        # Use service account token
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
    - context:
        cluster: local
        user: service-account
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig-in-cluster-latest
  namespace: kube-system
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - name: local
      cluster:
        server: https://porkadot-kubernetes-latest:6443
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
    - name: service-account
      user:
        # Use service account token
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
    - context:
        cluster: local
        user: service-account
